name: iOS UI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ui-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Resolve SPM dependencies
        run: xcodebuild -resolvePackageDependencies -scheme AudiusUITests
      
      - name: Create Simulator
        run: xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-2


      - name: Run UI Tests
        run: |
          xcodebuild test \
            -project Audius.xcodeproj \
            -scheme AudiusUITests \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            -only-testing:AudiusUITests \
            CODE_SIGNING_ALLOWED=NO